# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dac1983cc6fe030ab3456c4cd663bd1a7a64212e989ba80769e4fb3188b6a22f88eee3b8fa16f2abe4352ec3f12d604c41b730f4ea68476da2049054746e6cda

test:
  secret_key_base: 7f2a516ce4d5d224776cb13b52c3549ed51064b831cc48a124672d89f8536a890df40bb0b599c1b32cd950515615101e46c34b7a09e0df5ea4c402e6fcc0e004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
